### ISSUE TITLE
Depth and temperature profile not combined

### ISSUE THREAD

**Issue by mdjong4** [sumoDave/GarminDiveFitAppender#3] opened 2024-04-15 12:24 UTC
In the newly created append file, the depth and temperature charts aren't combined. The charts only show the data from the first dive.

**Comment by sumoDave** [comment] 2024-04-15 13:13
Cannot reproduce the issue. Can you attach your original FIT files?

**Comment by sumoDave** [comment] 2024-04-15 13:55
Fixed with Start Time issue.

**Closed as completed by sumoDave** 2024-04-15 13:55 UTC
